export enum ErrorMessages {
  INVALID_URL = "INVALID_URL",
  NETWORK_ERROR = "NETWORK_ERROR",
  PARSING_ERROR = "PARSING_ERROR",
  NO_DATA_FOUND = "NO_DATA_FOUND",
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
}