export enum ErrorMessages {
  INVALID_URL = "INVALID_URL",
  NETWORK_ERROR = "NETWORK_ERROR",
  PARSING_ERROR = "PARSING_ERROR",
  NO_DATA_FOUND = "NO_DATA_FOUND",
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_COMMAND = "INVALID_COMMAND",
  MISSING_ARGUMENTS = "MISSING_ARGUMENTS",
  INVALID_ARGUMENTS = "INVALID_ARGUMENTS",
}